/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ColumnType = IDL.Variant({
  'date' : IDL.Null,
  'text' : IDL.Null,
  'number' : IDL.Null,
});
export const ColumnDefinition = IDL.Record({
  'name' : IDL.Text,
  'colType' : ColumnType,
});
export const DatasetSchema = IDL.Record({
  'columns' : IDL.Vec(ColumnDefinition),
});
export const ChartData = IDL.Record({
  'labels' : IDL.Vec(IDL.Text),
  'values' : IDL.Vec(IDL.Float64),
});
export const ChartType = IDL.Variant({
  'bar' : IDL.Null,
  'pie' : IDL.Null,
  'none' : IDL.Null,
});
export const QueryResult = IDL.Record({
  'chartData' : IDL.Opt(ChartData),
  'chartType' : ChartType,
  'answer' : IDL.Text,
});
export const QueryRecord = IDL.Record({
  'id' : IDL.Nat,
  'result' : QueryResult,
  'question' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearSession' : IDL.Func([], [], []),
  'getDatasetSchema' : IDL.Func([], [IDL.Opt(DatasetSchema)], ['query']),
  'getQueryHistory' : IDL.Func([], [IDL.Vec(QueryRecord)], ['query']),
  'queryData' : IDL.Func([IDL.Text], [QueryResult], []),
  'setDataRows' : IDL.Func([IDL.Text], [], []),
  'setDatasetSchema' : IDL.Func([IDL.Vec(ColumnDefinition)], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ColumnType = IDL.Variant({
    'date' : IDL.Null,
    'text' : IDL.Null,
    'number' : IDL.Null,
  });
  const ColumnDefinition = IDL.Record({
    'name' : IDL.Text,
    'colType' : ColumnType,
  });
  const DatasetSchema = IDL.Record({ 'columns' : IDL.Vec(ColumnDefinition) });
  const ChartData = IDL.Record({
    'labels' : IDL.Vec(IDL.Text),
    'values' : IDL.Vec(IDL.Float64),
  });
  const ChartType = IDL.Variant({
    'bar' : IDL.Null,
    'pie' : IDL.Null,
    'none' : IDL.Null,
  });
  const QueryResult = IDL.Record({
    'chartData' : IDL.Opt(ChartData),
    'chartType' : ChartType,
    'answer' : IDL.Text,
  });
  const QueryRecord = IDL.Record({
    'id' : IDL.Nat,
    'result' : QueryResult,
    'question' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearSession' : IDL.Func([], [], []),
    'getDatasetSchema' : IDL.Func([], [IDL.Opt(DatasetSchema)], ['query']),
    'getQueryHistory' : IDL.Func([], [IDL.Vec(QueryRecord)], ['query']),
    'queryData' : IDL.Func([IDL.Text], [QueryResult], []),
    'setDataRows' : IDL.Func([IDL.Text], [], []),
    'setDatasetSchema' : IDL.Func([IDL.Vec(ColumnDefinition)], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };