/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QueryRecord {
    id: bigint;
    result: QueryResult;
    question: string;
    timestamp: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface QueryResult {
    chartData?: ChartData;
    chartType: ChartType;
    answer: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ColumnDefinition {
    name: string;
    colType: ColumnType;
}
export interface DatasetSchema {
    columns: Array<ColumnDefinition>;
}
export interface ChartData {
    labels: Array<string>;
    values: Array<number>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum ChartType {
    bar = "bar",
    pie = "pie",
    none = "none"
}
export enum ColumnType {
    date = "date",
    text = "text",
    number_ = "number"
}
export interface backendInterface {
    clearSession(): Promise<void>;
    getDatasetSchema(): Promise<DatasetSchema | null>;
    getQueryHistory(): Promise<Array<QueryRecord>>;
    queryData(question: string): Promise<QueryResult>;
    setDataRows(rows: string): Promise<void>;
    setDatasetSchema(columns: Array<ColumnDefinition>): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ChartData as _ChartData, ChartType as _ChartType, ColumnDefinition as _ColumnDefinition, ColumnType as _ColumnType, DatasetSchema as _DatasetSchema, QueryRecord as _QueryRecord, QueryResult as _QueryResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSession();
            return result;
        }
    }
    async getDatasetSchema(): Promise<DatasetSchema | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatasetSchema();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatasetSchema();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueryHistory(): Promise<Array<QueryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueryHistory();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueryHistory();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryData(arg0: string): Promise<QueryResult> {
        if (this.processError) {
            try {
                const result = await this.actor.queryData(arg0);
                return from_candid_QueryResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryData(arg0);
            return from_candid_QueryResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDataRows(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDataRows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDataRows(arg0);
            return result;
        }
    }
    async setDatasetSchema(arg0: Array<ColumnDefinition>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDatasetSchema(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDatasetSchema(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ChartType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartType): ChartType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ColumnDefinition_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColumnDefinition): ColumnDefinition {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ColumnType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColumnType): ColumnType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DatasetSchema_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DatasetSchema): DatasetSchema {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_QueryRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryRecord): QueryRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QueryResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryResult): QueryResult {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DatasetSchema]): DatasetSchema | null {
    return value.length === 0 ? null : from_candid_DatasetSchema_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChartData]): ChartData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    result: _QueryResult;
    question: string;
    timestamp: bigint;
}): {
    id: bigint;
    result: QueryResult;
    question: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        result: from_candid_QueryResult_n12(_uploadFile, _downloadFile, value.result),
        question: value.question,
        timestamp: value.timestamp
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chartData: [] | [_ChartData];
    chartType: _ChartType;
    answer: string;
}): {
    chartData?: ChartData;
    chartType: ChartType;
    answer: string;
} {
    return {
        chartData: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.chartData)),
        chartType: from_candid_ChartType_n15(_uploadFile, _downloadFile, value.chartType),
        answer: value.answer
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    columns: Array<_ColumnDefinition>;
}): {
    columns: Array<ColumnDefinition>;
} {
    return {
        columns: from_candid_vec_n4(_uploadFile, _downloadFile, value.columns)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    colType: _ColumnType;
}): {
    name: string;
    colType: ColumnType;
} {
    return {
        name: value.name,
        colType: from_candid_ColumnType_n7(_uploadFile, _downloadFile, value.colType)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bar: null;
} | {
    pie: null;
} | {
    none: null;
}): ChartType {
    return "bar" in value ? ChartType.bar : "pie" in value ? ChartType.pie : "none" in value ? ChartType.none : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: null;
} | {
    text: null;
} | {
    number: null;
}): ColumnType {
    return "date" in value ? ColumnType.date : "text" in value ? ColumnType.text : "number" in value ? ColumnType.number : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ColumnDefinition>): Array<ColumnDefinition> {
    return value.map((x)=>from_candid_ColumnDefinition_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueryRecord>): Array<QueryRecord> {
    return value.map((x)=>from_candid_QueryRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ColumnDefinition_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColumnDefinition): _ColumnDefinition {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ColumnType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColumnType): _ColumnType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    colType: ColumnType;
}): {
    name: string;
    colType: _ColumnType;
} {
    return {
        name: value.name,
        colType: to_candid_ColumnType_n20(_uploadFile, _downloadFile, value.colType)
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColumnType): {
    date: null;
} | {
    text: null;
} | {
    number: null;
} {
    return value == ColumnType.date ? {
        date: null
    } : value == ColumnType.text ? {
        text: null
    } : value == ColumnType.number ? {
        number_: null
    } : value;
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ColumnDefinition>): Array<_ColumnDefinition> {
    return value.map((x)=>to_candid_ColumnDefinition_n18(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
